### ISSUE TITLE
SyntaxError: Invalid or unexpected token  - while configuring the server

### ISSUE THREAD

**Issue by deepakkumpala** [appsecco/owasp-threat-dragon-gitlab#2]
SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1116:16)
    at Module._compile (internal/modules/cjs/loader.js:1164:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! owasp-threat-dragon-gitlab@0.4.19 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the owasp-threat-dragon-gitlab@0.4.19 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxxx\AppData\Roaming\npm-cache\_logs\2020-08-19T06_27_15_369Z-debug.log

**Comment by jgadsden** [comment]
Hello @kudlatiger - could you give more context on how the error was produced? was it started from the command line, and you had the environment variables set up OK?

Mike Goodwin's original Threat Dragon (from which owasp-threat-dragon-gitlab was developed) has been migrated to a new area in the OWASP github organisation area:
https://github.com/OWASP/threat-dragon-core

We hope that owasp-threat-dragon-gitlab cann be combined with this so it can be picked up by :
https://github.com/OWASP/threat-dragon-desktop
and
https://github.com/OWASP/threat-dragon
